//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autor
    {
        public Autor()
        {
            this.Libro = new HashSet<Libro>();
        }
    
        public int dni { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Libro> Libro { get; set; }
        public virtual Editorial Editorial { get; set; }
    }
}
